### ISSUE TITLE
Having trouble hosting the Whoops Rail Engine

### ISSUE THREAD

**Issue by alexw668** [flyingmachine/whoops#1]
I created a Rails app to host your Whoops Rails engine. When I run this app on my local machine, everything worked fine. I was able to log message to the mongodb via WhoopsLogger.log method. However, the same mechanism did not work when sending logging message to my rails app containing the Whoops Rails engine. I got an internal server error. Looking at Rails log file, it contains errors like this:

Started POST "/events/" for 170.36.242.221 at Fri Aug 12 17:13:53 -0700 2011
  Processing by EventsController#create as JSON
  Parameters: {"event"=>{"details"=>nil, "service"=>"MyService", "event_group_identifier"=>"My App", "event_time"=>Fri Aug 12 17:13:28 -0700 2011, "environment"=>"development", "message"=>"My logging message", "event_type"=>"debug", "logger_strategy_name"=>"default::basic"}}

Sent mail to #Mongoid::Criteria:0x7fc51a502170 (8ms)
Completed 500 Internal Server Error in 22ms

ArgumentError (A sender (Return-Path, Sender or From) required to send a message):

Any idea why this happens?

My Rails app is running Rails 3.0.9 on Ruby 1.8.7.

Appreciate your any help!

Sincerely,
Alex

**Comment by alexw668** [comment]
What I meant was that I got the error when the Rails app is running on another machine.

**Comment by alexw668** [comment]
I did not mean to close this issue. :)

**Comment by flyingmachine** [comment]
I'm not immediately sure why this is happening, but I'll look into it. It might take me a couple more days, though :)

**Comment by alexw668** [comment]
Thanks!

It may have something to do with this line in EventGroup#send_notifications

   Whoops::NotificationMailer.event_notification(self, matcher.matches).deliver

where nothing is matched by the matcher. Looking at my mongodb, I don't see any record, or any collection (for, e.g., NotificationRule) being created/added, for that matter.

**Comment by flyingmachine** [comment]
OK, I've made some changes that should have fixed it. I haven't checked with an actual server yet, but will do that tomorrow. Sorry it took me awhile! Work really picked up, and I haven't had much time.

**Comment by alexw668** [comment]
Thanks!
