### ISSUE TITLE
Boosting Performance?

### ISSUE THREAD

**Issue by alexw668** [flyingmachine/whoops#2]
We've been running the Whoops for a while and we've accumulated a bunch of logging messages. Now when we tried to examine some of messages, the response from the site hosting the Whoops engine is very slow. 

I can see two reasons why that's the case. 1) By default, the whoops_events collection is not capped (we currently have more than 500k events being stored); 2) no indexes were created on whoops_events collection. Indexing on event_group_id, event_time, and keywords should help.

Regarding capped collection for whoops_events, is it possible and safe for us to convert the whoops_events collection into a capped one without dropping the collection and recreating it? 

It would be great if you could make some changes to address this issue. 

Thanks!
Alex

**Comment by alexw668** [comment]
I added the index to my forked version; and I also made the whoops_events collection capped (at 1GB). Our log server now runs much faster!!

**Comment by flyingmachine** [comment]
That's awesome! Could you do a pull request?

I think that in addition to capping the collection, it would be good to have a way to delete old events. There's no support for that right now, and I haven't thought it through, but in the past I've definitely been annoyed with having to wade through reams of old, irrelevant logs.
